In [25]:
import pandas as pd

## Loading the Dataset

In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/JuliaData/CSV.jl/refs/heads/main/test/testfiles/Sacramentorealestatetransactions.csv')
df.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

## Finding the Number of Columns in the dataset

In [27]:
num_cols = len(df.columns)
print(f'This dataset has {num_cols} columns')

This dataset has 12 columns

## Finding the Mean of the House Prices

In [28]:
mean_house_price = df.price.mean()
print(f'The mean price of houses in this dataset is ${mean_house_price:,.2f}')

The mean price of houses in this dataset is $234,144.26

## Finding the Median of the House Prices

In [29]:
median_house_price = df.price.median()
print(f'The median price of houses in this dataset is ${median_house_price:,.2f}')

The median price of houses in this dataset is $213,750.00

## Finding the Different Types of Property in the Dataset

In [30]:
different_property_types = df.type.unique()
formatted_prop_types = ', '.join(map(str, different_property_types))
print(f'The different types of properties in the dataset are: {formatted_prop_types}')

The different types of properties in the dataset are: Residential, Condo, Multi-Family, Unkown

## Finding the Max Price of a Condo in the Dataset

In [31]:
max_condo_price = df[(df.type == 'Condo')].price.max()
print(f'The max price of a condo is ${max_condo_price:,.2f}')

The max price of a condo is $360,000.00

## Find the Mean of Each Type of Property in the Dataset

In [32]:
mean_prop_type_prices = df[['price', 'type']].groupby("type").mean()
mean_prop_type_prices

                      price
type
Condo         150082.185185
Multi-Family  224534.692308
Residential   239186.162486
Unkown        275000.000000

## Finding the Count of Different Property Types in the Dataset

In [33]:
prop_types_count = df.type.value_counts()
prop_types_count

type
Residential     917
Condo            54
Multi-Family     13
Unkown            1
Name: count, dtype: int64